### ISSUE TITLE
Deleted articles render as empty articles

### ISSUE THREAD

**Issue by smai-f** [molebox/gatsby-theme-pocket#12]
After deleting articles from one's Pocket dashboard, they are still returned as part of the response from the Pocket API with a bunch of null fields, and then they render like so:

![image](https://user-images.githubusercontent.com/5832646/93419843-14a88900-f86b-11ea-86d2-ede41ec2b22f.png)

Would be great to exclude these. Again, happy to contribute if you're open to it!

**Comment by molebox** [comment]
Good catch! Yep, happy for the help
